add config for rqfiles dir in wn & sn
pastelnetwork/gonode pull request #116
Opened 2021-07-12 22:46 UTC by mateeullahmalik

2021-07-13 17:45 UTC, mykytaccode0 requested changes
Missing the code to create the directory on the machine, need to do similar to:
		if err := os.MkdirAll(config.TempDir, os.ModePerm); err != nil {
			return errors.Errorf("could not create temp-dir %q, %w", config.TempDir, err)
		}

2021-07-14 15:33 UTC, mykytaccode0 approved these changes

2021-07-16 08:49 UTC, pjenys0 commented on walletnode/cmd/app.go
> +		if err := os.MkdirAll(config.RqFilesDir, os.ModePerm); err != nil {
could you put directly `0777` than os.ModePerm? Because os.ModePerm is usually used as bit mask than directly.

2021-07-16 14:49 UTC, pjenys0 approved these changes
LGTM!

2021-07-16 14:50 UTC, merged