Psl 149 modify rqi ds files
pastelnetwork/gonode pull request #261
Opened 2021-12-11 09:20 UTC by mateeullahmalik

2021-12-12 13:49 UTC, nguyen202 approved these changes
It's fine, but please confirm type of DDAndFingerprintsIc as commented in https://github.com/pastelnetwork/gonode/pull/260/files

2021-12-12 21:33 UTC, a-ok123 requested changes

2021-12-12 21:33 UTC, a-ok123 commented on walletnode/services/artworkregister/helper.go
> +func gen4bytesRandomNum() int {
should just use rand.Uint32()

2021-12-12 21:33 UTC, a-ok123 commented on walletnode/services/artworkregister/task.go
> +	task.ddAndFingerprintsIc = uint16(gen4bytesRandomNum())
why do you cut it into 2 bytes?

2021-12-13 16:07 UTC, a-ok123 approved these changes

2021-12-13 16:22 UTC, merged