Node connection improvement
pastelnetwork/gonode pull request #27
Opened 2021-05-11 18:20 UTC by levkoburburas

* Keep _Pastel ID_ in the `supernode` config file (instead of retrieving by pastel api)
* Improve `supernode` connections in the task.

2021-05-12 01:39 UTC, a-ok123 approved these changes

2021-05-12 01:40 UTC, a-ok123 commented on walletnode/services/artworkregister/task.go
> +				return errors.Errorf("%q closed the connection", node.address)
may be "unexpectedly" ?

2021-05-12 01:47 UTC, a-ok123 requested changes
Can we read pastel-api data from `pastel.conf`?  (somethings would be defaulted if missing from pastel.conf - like port)

Just a note: About node's own port in config - should be documented that port here must match the port in masternode.conf

2021-05-12 12:23 UTC, levkoburburas commented on walletnode/services/artworkregister/task.go
> +				return errors.Errorf("%q closed the connection", node.address)
Definitely, thanks for the hint, fixed.

2021-05-12 12:26 UTC, levkoburburas commented
> Can we read pastel-api data from `pastel.conf`? (somethings would be defaulted if missing from pastel.conf - like port)
> 
> Just a note: About node's own port in config - should be documented that port here must match the port in masternode.conf

Sure, agree, working on the implementation.

2021-05-12 14:39 UTC, levkoburburas commented on common/configurer/linux.go
> +var defaultConfigPaths = []string{".", "$HOME/.pastel"}
Is it correct path for linux `"$HOME/.pastel"`?

2021-05-12 14:39 UTC, levkoburburas commented on common/configurer/windows.go
> +var defaultConfigPaths = []string{".", "$HOME/.pastel"}
What is correct path for windows?

2021-05-12 14:52 UTC, levkoburburas commented
> Can we read pastel-api data from `pastel.conf`? (somethings would be defaulted if missing from pastel.conf - like port)
> 
> Just a note: About node's own port in config - should be documented that port here must match the port in masternode.conf

1. The highest priority of pastel-api settings is from walletnode config.
2. By default pastel (external) config `pastel.conf` is being looked for in the default path (depends on OS) and in the path of the walletnode binary.
3. The filepath to pastel (external) config can be also overwrited in CLI by flag `pastel-config-file` or in walletnode config:
```
pastel-api:
   config-file: /path/to/pastel.conf
```
4. If some settings  is missed in the walletnode config it takes from pastel (external) config.
```
pastel-api:
   port: 19932
```
the rest (hostname,username,password) will be taken from pastel (external) config.

5. If not specified neither in walletnode nor paste configs, it has default settings for (hostname and port).

2021-05-12 15:05 UTC, levkoburburas commented
You can also looking into [examples](https://github.com/pastelnetwork/gonode/tree/node-connection-improvement/walletnode/examples/configs)

2021-05-12 15:14 UTC, levkoburburas commented
One more, `node` has also default settings, so you can run without specified any configs, and it will works 
![image](https://user-images.githubusercontent.com/62853952/117999848-f0e00900-b34d-11eb-9bf8-760e0f25fe1c.png)

2021-05-16 03:34 UTC, a-ok123 approved these changes

2021-05-16 03:43 UTC, merged