[WIP][PSL-108] Process Open API request - `dupe detection` - in WN and SN
pastelnetwork/gonode pull request #285
Opened 2021-12-31 14:23 UTC by bacnh8

Work in progress

Ref: https://pastel.wiki/en/Architecture/OpenAPI/Sense

2022-01-07 10:05 UTC, mateeullahmalik commented on pastel/common.go
> +	CascadeFee float64 `json:"cascadefee"`
please double check that json tag not snake case like sense_fee

2022-01-07 10:28 UTC, mateeullahmalik commented on supernode/services/senseregister/node.go
> +type Node struct {
I think we can combine Node & Nodes used al across project.

2022-01-07 10:29 UTC, mateeullahmalik commented on supernode/services/senseregister/service.go
> +// Service represent artwork service.
please correct the comment here. 
its sense not artwork

2022-01-07 10:30 UTC, mateeullahmalik commented on supernode/services/senseregister/service.go
> +	*artwork.Storage
move storage to a common location? so sense doesn't import "artwork"?

2022-01-07 10:32 UTC, mateeullahmalik commented on walletnode/api/design/sense.go
> +			GET("/start/{taskId}/state")
I think "start" is not needed here?

2022-01-07 10:44 UTC, mateeullahmalik requested changes
Move some commonly used code (I've commented) out of artwork package to a common location to make it generic. Few minor things. 
Integration tests are failing as well.. Please fix.
Otherwise LGTM!
Nice work!

2022-01-10 16:54 UTC, a-ok123 submitted a review, later dismissed
Conditionally approving, requires re-factoring and verifiaction

2022-01-11 00:23 UTC, mateeullahmalik approved these changes

2022-01-11 01:45 UTC, a-ok123 approved these changes

2022-01-11 01:46 UTC, merged