Move pastel utility repo to gonode
pastelnetwork/gonode pull request #83
Opened 2021-06-09 12:27 UTC by s4kibs4mi

Moved `Pastel-Utility` from individual repo to this repo. Also refactored the code to make the standard same as supernode and walletnode.

2021-06-09 20:36 UTC, levkoburburas requested changes
I only partly reviewed `cmd/init.go`. 
The code is poorly thought out and contains a lot of silly things.

2021-06-09 20:36 UTC, levkoburburas commented on tools/pastel-utility/cmd/init.go
> +			if err != nil {
```suggestion
		if _, err := os.Stat(zksnarkParamsPath); err == nil && !force {
			log.WithContext(ctx).Infof("zksnark file %s already exists and force set to %v", zksnarkParamsPath, force)
			continue
		}
		
		out, err := os.Create(zksnarkParamsPath)
		if err != nil {
		....
```

Write simpler, no need to nest large chunks of code deeper.

2021-06-09 20:36 UTC, levkoburburas commented on tools/pastel-utility/cmd/init.go
> +	// ok := resp.StatusCode == http.StatusOK
What to do with it? Delete or add comment  
```go
// TODO: ....
or 
// NOTE: ....
```

2021-06-09 20:36 UTC, levkoburburas commented on tools/pastel-utility/cmd/init.go
> +		os.Exit(0)
Again, It looks like this was done on purpose.
Have you ever heard about `<-ctx.Done()` ?

2021-06-09 20:36 UTC, levkoburburas commented on tools/pastel-utility/cmd/init.go
> +	walletConfigPath := fmt.Sprintf("%s/wallet.env", walletNodePath)
```suggestion
	walletConfigPath := filepath.Join(walletNodePath, "walletnode.yml")
```
1. Do you realize that windows OS has `\` back slash? Use `fmt.Sprintf` to concat paths is silly
2. `wallet.env` this is wrong filename! Who did tell you that config name of `walletnode` is `wallet.env` ? Moreover you are use `v.SetConfigType("json")`. It's weird 
3. Config is not needed to be placed in `work-dir`

2021-06-09 20:36 UTC, levkoburburas commented on tools/pastel-utility/cmd/init.go
> +	})
Why do you repeat it in each function? Is there no other way to write once?

2021-07-25 02:34 UTC, closed without merging

2021-07-25 02:35 UTC, a-ok123 commented
outdated